# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tecxlab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'AWSCognito'
  pod 'AWSMobileClient'
  pod 'AWSPinpoint'
  
  pod 'IQKeyboardManagerSwift'
  pod 'LGSideMenuController'
  
  
  pod 'SDWebImage'
  pod 'DropDown'
  
  
  pod 'Alamofire', '~> 5.1.0'
  pod 'NVActivityIndicatorView'
  
  pod 'SwiftKeychainWrapper'
  # Pods for tecxlab

end
